### ISSUE TITLE
Error when running "make"

### ISSUE THREAD

**Issue by Meng-37** [epfml/sent2vec#54]
Hello!
    When I try to compile the library as Setup & Requirements suggests by running ``make`` command, errors pop up as below:
> c++ -pthread -std=c++0x -O3 -funroll-loops -c src/dictionary.cc
In file included from src/dictionary.cc:10:
src/dictionary.h:55: error: ISO C++ forbids initialization of member ‘pruneidx_size_’
src/dictionary.h:55: error: making ‘pruneidx_size_’ static
src/dictionary.h:55: error: ISO C++ forbids in-class initialization of non-const static member ‘pruneidx_size_’
src/dictionary.cc: In member function ‘void fasttext::Dictionary::threshold(int64_t, int64_t)’:
src/dictionary.cc:261: error: expected primary-expression before ‘[’ token
src/dictionary.cc:261: error: expected primary-expression before ‘]’ token
src/dictionary.cc:261: error: expected primary-expression before ‘const’
src/dictionary.cc:261: error: expected primary-expression before ‘const’
src/dictionary.cc:265: error: expected primary-expression before ‘[’ token
src/dictionary.cc:265: error: expected primary-expression before ‘]’ token
src/dictionary.cc:265: error: expected primary-expression before ‘const’
src/dictionary.cc:269: error: ‘class std::vector<fasttext::entry, std::allocator<fasttext::entry> >’ has no member named ‘shrink_to_fit’
src/dictionary.cc: In member function ‘std::vector<long int, std::allocator<long int> > fasttext::Dictionary::getCounts(fasttext::entry_type) const’:
src/dictionary.cc:292: error: expected initializer before ‘:’ token
src/dictionary.cc:295: error: expected primary-expression before ‘return’
src/dictionary.cc:295: error: expected ‘;’ before ‘return’
src/dictionary.cc:295: error: expected primary-expression before ‘return’
src/dictionary.cc:295: error: expected ‘)’ before ‘return’
src/dictionary.cc: In member function ‘void fasttext::Dictionary::addNgrams(std::vector<int, std::allocator<int> >&, int32_t, int32_t, std::minstd_rand&) const’:
src/dictionary.cc:322: error: ‘uniform_int_distribution’ is not a member of ‘std’
src/dictionary.cc:322: error: expected primary-expression before ‘>’ token
src/dictionary.cc:322: error: ‘uniform’ was not declared in this scope
src/dictionary.cc: In member function ‘int32_t fasttext::Dictionary::getLine(std::istream&, std::vector<int, std::allocator<int> >&, std::vector<int, std::allocator<int> >&, std::vector<int, std::allocator<int> >&, std::minstd_rand&) const’:
src/dictionary.cc:357: error: ‘uniform_real_distribution’ is not a member of ‘std’
src/dictionary.cc:357: error: expected primary-expression before ‘>’ token
src/dictionary.cc:357: error: ‘uniform’ was not declared in this scope
src/dictionary.cc: In member function ‘void fasttext::Dictionary::save(std::ostream&) const’:
src/dictionary.cc:426: error: expected initializer before ‘:’ token
src/dictionary.cc:430: error: expected primary-expression before ‘}’ token
src/dictionary.cc:430: error: expected ‘;’ before ‘}’ token
src/dictionary.cc:430: error: expected primary-expression before ‘}’ token
src/dictionary.cc:430: error: expected ‘)’ before ‘}’ token
src/dictionary.cc:430: error: expected primary-expression before ‘}’ token
src/dictionary.cc:430: error: expected ‘;’ before ‘}’ token
src/dictionary.cc: In member function ‘void fasttext::Dictionary::prune(std::vector<int, std::allocator<int> >&)’:
src/dictionary.cc:474: error: expected initializer before ‘:’ token
src/dictionary.cc:478: error: could not convert ‘((std::vector<int, std::allocator<int> >*)idx)->std::vector<_Tp, _Alloc>::insert [with _InputIterator = __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, _Tp = int, _Alloc = std::allocator<int>](((std::vector<int, std::allocator<int> >*)idx)->std::vector<_Tp, _Alloc>::end [with _Tp = int, _Alloc = std::allocator<int>](), ngrams.std::vector<_Tp, _Alloc>::begin [with _Tp = int, _Alloc = std::allocator<int>](), ngrams.std::vector<_Tp, _Alloc>::end [with _Tp = int, _Alloc = std::allocator<int>]())’ to ‘bool’
src/dictionary.cc:479: error: expected primary-expression before ‘}’ token
src/dictionary.cc:479: error: expected ‘)’ before ‘}’ token
src/dictionary.cc:479: error: expected primary-expression before ‘}’ token
src/dictionary.cc:479: error: expected ‘;’ before ‘}’ token
make: *** [dictionary.o] Error 1

I assume it's about c++, but I'm not familiar with that, can someone help?

Also I tried running ``python setup.py build_ext`` from ``./sent2vec/src``, but again errors occur:
> running build_ext
building 'sent2vec' extension
gcc -pthread -B /home/python/anaconda3/envs/termExtraction/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/python/anaconda3/envs/termExtraction/lib/python3.6/site-packages/numpy/core/include -I/home/python/anaconda3/envs/termExtraction/include/python3.6m -c sent2vec.cpp -o build/temp.linux-x86_64-3.6/sent2vec.o -std=c++0x -Wno-cpp -pthread -Wno-sign-compare
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
In file included from /home/python/anaconda3/envs/termExtraction/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816,
                 from /home/python/anaconda3/envs/termExtraction/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/python/anaconda3/envs/termExtraction/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from sent2vec.cpp:663:
/home/python/anaconda3/envs/termExtraction/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
In file included from sent2vec.cpp:671:
fasttext.h:18:18: error: atomic: No such file or directory
In file included from fasttext.h:23,
                 from sent2vec.cpp:671:
dictionary.h:55: error: ISO C++ forbids initialization of member ‘pruneidx_size_’
dictionary.h:55: error: making ‘pruneidx_size_’ static
dictionary.h:55: error: ISO C++ forbids in-class initialization of non-const static member ‘pruneidx_size_’
In file included from qmatrix.h:25,
                 from fasttext.h:25,
                 from sent2vec.cpp:671:
productquantizer.h:26: error: ISO C++ forbids initialization of member ‘nbits_’
productquantizer.h:26: error: making ‘nbits_’ static
productquantizer.h:27: error: ISO C++ forbids initialization of member ‘ksub_’
productquantizer.h:27: error: making ‘ksub_’ static
productquantizer.h:28: error: ISO C++ forbids initialization of member ‘max_points_per_cluster_’
productquantizer.h:28: error: making ‘max_points_per_cluster_’ static
productquantizer.h:29: error: ISO C++ forbids initialization of member ‘max_points_’
productquantizer.h:29: error: making ‘max_points_’ static
productquantizer.h:30: error: ISO C++ forbids initialization of member ‘seed_’
productquantizer.h:30: error: making ‘seed_’ static
productquantizer.h:31: error: ISO C++ forbids initialization of member ‘niter_’
productquantizer.h:31: error: making ‘niter_’ static
productquantizer.h:32: error: ISO C++ forbids initialization of member ‘eps_’
productquantizer.h:32: error: making ‘eps_’ static
In file included from sent2vec.cpp:671:
fasttext.h:46: error: ISO C++ forbids declaration of ‘atomic’ with no type
fasttext.h:46: error: invalid use of ‘::’
fasttext.h:46: error: expected ‘;’ before ‘<’ token
cc1plus: warning: unrecognized command line option "-Wno-cpp"
error: command 'gcc' failed with exit status 1

Information against the OS is 
> Linux slaver01 2.6.32-696.el6.x86_64 #1 SMP Tue Mar 21 19:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux``

Thanks in advance!

**Comment by mpagli** [comment]
Can you check your g++ version ? `g++ --version`

**Comment by Meng-37** [comment]
Thank you for replying! Information against the g++ version is:
> g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)

I can tell that ``2012`` seems out-dated. Do I need to install a newer version, and which version shall I choose if so?

**Comment by Meng-37** [comment]
Hi there! Sorry to report this late, but I still encounter problems compiling ``fasttext.cc`` even after updating g++ to 7.3.0. Detailed information is as below:
> src/fasttext.cc: In member function ‘void fasttext::FastText::printLabelStats(std::istream&, int32_t, fasttext::real) const’:
src/fasttext.cc:445:40: warning: ‘void fasttext::FastText::writePerLabelMetrics(std::ostream&, fasttext::Meter&) const’ is deprecated: This function is deprecated and will be removed along with `printLabelStats`. [-Wdeprecated-declarations]
   writePerLabelMetrics(std::cout, meter);
                                        ^
In file included from src/fasttext.cc:10:0:
src/fasttext.h:126:8: note: declared here
   void writePerLabelMetrics(std::ostream&, Meter&) const;
        ^~~~~~~~~~~~~~~~~~~~
c++ -pthread -std=c++0x -O3 -funroll-loops args.o dictionary.o productquantizer.o matrix.o qmatrix.o  vector.o model.o utils.o fasttext.o src/main.cc -o fasttext
src/main.cc: In function ‘void test(const std::vector<std::__cxx11::basic_string<char> >&)’:
src/main.cc:159:51: warning: ‘void fasttext::FastText::writePerLabelMetrics(std::ostream&, fasttext::Meter&) const’ is deprecated: This function is deprecated and will be removed along with `printLabelStats`. [-Wdeprecated-declarations]
     fasttext.writePerLabelMetrics(std::cout, meter);
                                                   ^
In file included from src/main.cc:15:0:
src/fasttext.h:126:8: note: declared here
   void writePerLabelMetrics(std::ostream&, Meter&) const;
        ^~~~~~~~~~~~~~~~~~~~
fasttext.o: In function `fasttext::FastText::test(std::istream&, int, float, fasttext::Meter&) const':
fasttext.cc:(.text+0x1960): undefined reference to `fasttext::Meter::log(std::vector<int, std::allocator<int> > const&, std::vector<std::pair<float, int>, std::allocator<std::pair<float, int> > > const&)'
fasttext.o: In function `fasttext::FastText::writePerLabelMetrics(std::ostream&, fasttext::Meter&) const':
fasttext.cc:(.text+0x261b): undefined reference to `fasttext::Meter::precision(int)'
fasttext.cc:(.text+0x26ca): undefined reference to `fasttext::Meter::recall(int)'
fasttext.cc:(.text+0x2811): undefined reference to `fasttext::Meter::f1Score(int)'
fasttext.o: In function `fasttext::FastText::test(std::istream&, int, float)':
fasttext.cc:(.text+0x2fb1): undefined reference to `fasttext::Meter::recall() const'
fasttext.cc:(.text+0x2fc1): undefined reference to `fasttext::Meter::precision() const'
/tmp/ccvKyczq.o: In function `test(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
main.cc:(.text+0x1278): undefined reference to `fasttext::Meter::writeGeneralMetrics(std::ostream&, int) const'
/tmp/ccvKyczq.o: In function `quantize(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
main.cc:(.text+0x142e): undefined reference to `fasttext::Args::parseArgs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
/tmp/ccvKyczq.o: In function `train(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)':
main.cc:(.text+0x1999): undefined reference to `fasttext::Args::parseArgs(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
collect2: error: ld returned 1 exit status
make: *** [fasttext] Error 1

Suggestions of possible directions for resolving this problem are appreciated!

**Comment by nguyenxuanhoi2903** [comment]
When I try to compile the library as Setup & Requirements suggests by running make command, errors pop up as below:
c++ -pthread -std=c++0x -O3 -funroll-loops args.o dictionary.o productquantizer.o matrix.o shmem_matrix.o qmatrix.o vector.o model.o utils.o fasttext.o src/main.cc -o fasttext -lrt
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fasttext] Error 1
how to fix on macbook

**Comment by hovikgas** [comment]
I have the same exact issue as you, @nguyenxuanhoi2903, did you ever get it to work?

**Comment by guptaprkhr** [comment]
Closing the issue due to lack of activity. 
Will reopen it if the error still persists with the new versions.
